name: hillcrest_finance
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_riverpod: ^3.0.3
  riverpod: ^3.0.3
  auto_route: ^10.2.0
  hooks_riverpod: ^3.0.3
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  smooth_page_indicator: ^1.2.1
  pin_code_fields: ^8.0.1
  intl_phone_field: ^3.2.0
  shimmer: ^3.0.0
  overlay_support: ^2.1.0
  mime: ^2.0.0
  flutter_image_compress: ^2.4.0
  dio: ^5.9.0
  sentry_flutter: ^9.8.0
  pretty_dio_logger: ^1.4.0
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_secure_storage: ^9.2.4
  flutter_hooks: ^0.21.3+1
  retrofit: ^4.9.0
  flutter_native_splash: ^2.4.7
  json_annotation: ^4.9.0 # Added for json_serializable
  freezed_annotation: ^3.1.0
  awesome_dialog: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_annotation: ^3.0.3
  riverpod_generator: ^3.0.3
  auto_route_generator: ^10.2.6
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  retrofit_generator: ^10.0.0
  freezed: ^3.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/hillcrest_images/
    - assets/fonts/
    - .env

  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter-Regular.otf
           weight: 400
         - asset: assets/fonts/Inter-Bold.otf
           weight: 700
         - asset: assets/fonts/Inter-Thin.otf
           weight: 300
     - family: Cabin
       fonts:
         - asset: assets/fonts/Cabin-Bold.ttf
           weight: 700
         - asset: assets/fonts/Cabin-Medium.ttf
           weight: 500
         - asset: assets/fonts/Cabin-Regular.ttf
           weight: 400

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/hillcrest_images/hillcrest_logo.png
